### ISSUE TITLE
improve unittests

### ISSUE THREAD

**Issue by grindhold** [grindhold/libgtkflow#14]
we need more tests

**Comment by grindhold** [comment]
when we come to a conclusion in #30 , @esodan could proceed writing nice unittests for gflow, so we become more stable.

**Comment by grindhold** [comment]
tests do not compile right now due to a missing file that has been referenced in the Makefile.am, but does not exist.
@esodan do you plan to write this file or was this some work in progress that was not planned to be committed?

**Comment by esodan** [comment]
I've added missed file.

Modified tests for GtkFlow.NodeView and found error message:

libgtkflow/test/.libs/lt-gflow_test:6189): Pango-CRITICAL **: pango_layout_set_markup_with_accel: assertion 'markup != NULL' failed
FAIL

Could you review it in order to continue testing please?

**Comment by grindhold** [comment]
lolwut. on my system it SIGTRAPs somewhere when initializing the Gtk.Box that is to be the defaultvalue of action_area.

```#0  0x00007ffff5bd0d00 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff5bd0f3f in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7656ddc in gtk_css_provider_parsing_error (provider=<optimized out>, 
    section=<optimized out>, error=0x688130)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:1256
#3  0x00007ffff5e9f2d5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff5eb0f32 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff5eb9698 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff5eb98ff in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff765417e in _gtk_css_parser_take_error (parser=<optimized out>, error=0x6349b0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssparser.c:175
#8  0x00007ffff7654246 in _gtk_css_parser_error (parser=parser@entry=0x7fffe80074a0, 
    format=format@entry=0x7ffff789aeac "Theming engine '%s' not found")
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssparser.c:195
#9  0x00007ffff76492fc in _gtk_css_engine_value_parse (parser=0x7fffe80074a0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssenginevalue.c:124
#10 0x00007ffff76575c0 in parse_declaration (ruleset=0x7fffffffd350, scanner=0x7fffe80074d0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2434
#11 parse_declarations (ruleset=<optimized out>, scanner=<optimized out>)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2542
#12 parse_ruleset (scanner=0x7fffe80074d0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2574
#13 parse_statement (scanner=0x7fffe80074d0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2603
#14 parse_stylesheet (scanner=0x7fffe80074d0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2619
#15 gtk_css_provider_load_internal (css_provider=0x637fa0, parent=parent@entry=0x7fffe8009470, 
    file=file@entry=0x6ba0e0, text=<optimized out>, text@entry=0x0, error=error@entry=0x0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2735
#16 0x00007ffff7657b0d in parse_import (scanner=0x7fffe8009470)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2082
#17 parse_at_keyword (scanner=0x7fffe8009470)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2330
#18 parse_statement (scanner=0x7fffe8009470)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2601
#19 parse_stylesheet (scanner=0x7fffe8009470)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2619
#20 gtk_css_provider_load_internal (css_provider=0x637fa0, parent=parent@entry=0x7fffe8009690, 
    file=file@entry=0x6a6ee0, text=<optimized out>, text@entry=0x0, error=error@entry=0x0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2735
#21 0x00007ffff7657b0d in parse_import (scanner=0x7fffe8009690)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2082
#22 parse_at_keyword (scanner=0x7fffe8009690)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2330
#23 parse_statement (scanner=0x7fffe8009690)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2601
#24 parse_stylesheet (scanner=0x7fffe8009690)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2619
#25 gtk_css_provider_load_internal (css_provider=css_provider@entry=0x637fa0, parent=parent@entry=0x0, 
    file=file@entry=0x6a6ea0, text=<optimized out>, text@entry=0x0, error=error@entry=0x0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2735
#26 0x00007ffff765869a in gtk_css_provider_load_from_file (css_provider=css_provider@entry=0x637fa0, 
    file=file@entry=0x6a6ea0, error=error@entry=0x0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2837
#27 0x00007ffff7658726 in gtk_css_provider_load_from_path (css_provider=0x637fa0, path=<optimized out>, 
    error=0x0) at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:2871
#28 0x00007ffff76589dd in _gtk_css_provider_load_named (provider=0x637fa0, name=<optimized out>, 
    variant=<optimized out>) at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkcssprovider.c:3097
#29 0x00007ffff777eb26 in settings_update_theme (settings=settings@entry=0x637f50)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtksettings.c:3185
#30 0x00007ffff777ef4d in settings_init_style (settings=0x637f50)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtksettings.c:1818
#31 gtk_settings_get_for_screen (screen=<optimized out>)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtksettings.c:1867
#32 0x00007ffff7793983 in gtk_style_context_init (style_context=0x631130)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkstylecontext.c:425
#33 0x00007ffff5ec0f99 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff5ea4867 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff5ea625d in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff5ea69f4 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff7790e39 in gtk_style_context_new ()
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkstylecontext.c:994
#38 0x00007ffff75b27af in _gtk_style_new_for_path (screen=0x65e0c0, path=path@entry=0x674a60)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/deprecated/gtkstyle.c:853
#39 0x00007ffff75b282e in gtk_style_new ()
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/deprecated/gtkstyle.c:887
#40 0x00007ffff75b549d in gtk_widget_get_default_style_for_screen (screen=0x65e0c0)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/deprecated/gtkstyle.c:4023
#41 gtk_widget_get_default_style ()
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/deprecated/gtkstyle.c:4053
#42 0x00007ffff7830d75 in gtk_widget_init (widget=<optimized out>)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkwidget.c:4510
#43 0x00007ffff5ec0f57 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff5ea4867 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff5ea66a5 in g_object_new_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff5ea69e1 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007ffff75fcde5 in gtk_box_new (orientation=<optimized out>, spacing=<optimized out>)
    at /build/gtk+3.0-8FBlWQ/gtk+3.0-3.16.4/./gtk/gtkbox.c:2026
#48 0x00000000004066cc in gtk_flow_test_test_app_instance_init (self=0x680710)
    at /home/grindhold/git/libgtkflow/test/gtkflow-test-app-class.vala:27
#49 0x00007ffff5ec0f57 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#50 0x00007ffff5ea4867 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#51 0x00007ffff5ea625d in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#52 0x00007ffff5ea69f4 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#53 0x000000000040635d in gtk_flow_test_test_app_construct (object_type=<optimized out>)
    at /home/grindhold/git/libgtkflow/test/gtkflow-test-app-class.vala:34
---Type <return> to continue, or q <return> to quit---
#54 0x000000000040707e in gtk_flow_test_gui_node_test_construct (object_type=<optimized out>)
    at /home/grindhold/git/libgtkflow/test/gtkflow-node-test.vala:26
#55 gtk_flow_test_gui_node_test_new () at /home/grindhold/git/libgtkflow/test/gtkflow-node-test.vala:24
#56 0x00000000004070a6 in __lambda15_ ()
    at /home/grindhold/git/libgtkflow/test/gtkflow-node-test.vala:58
#57 ___lambda15__gcallback () at /home/grindhold/git/libgtkflow/test/gtkflow-node-test.vala:56
#58 0x00007ffff5bef453 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#59 0x00007ffff5bef622 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#60 0x00007ffff5bef98b in g_test_run_suite () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#61 0x00007ffff5bef9c1 in g_test_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#62 0x000000000040299d in gflow_test_main_main (args=0x7fffffffe658, args_length1=1)
    at /home/grindhold/git/libgtkflow/test/gflow-test.vala:33
#63 0x00007ffff51bbb45 in __libc_start_main (main=0x4026a0 <main>, argc=1, argv=0x7fffffffe658, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe648)
    at libc-start.c:287
#64 0x00000000004026d5 in _start ()
```

**Comment by esodan** [comment]
Could you provide more than info about your build system?

Do you have themes installed?

**Comment by grindhold** [comment]
yeah indeed. using adwaita instead of custom theme solves the problem.

**Comment by grindhold** [comment]
@esodan 

i fixed the bug in the ui-test.
